spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: jing
    password: jing123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # Options: none, update, create, create-drop, validate
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
